services:
  fast-api: 
    container_name: fast_api_hh
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/fast_api_hh
    env_file: .env
    command: >
      sh -c "uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - database_fast

  database_fast: 
    container_name: postgres_fast_hh
    image: postgres:14.7-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_fast_hh:/var/lib/postgresql/data/

volumes:
  postgres_fast_hh:
