services:
  fast-api: 
    container_name: fast_api_hh
    build:
      context: .
    ports:
      - "8088:8088"
    volumes:
      - .:/fast_api_hh
    env_file: .env
    command: >
      sh -c "uvicorn src.main:app --host 0.0.0.0 --port 8088 --reload"
    depends_on:
      - database_fast

  database_fast: 
    container_name: database_fast_hunter
    image: postgres:14.7-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_fast_hh:/var/lib/postgresql/data/

volumes:
  postgres_fast_hh:
