"""hr add email

Revision ID: 39aea01afdd5
Revises: 3b1445711430
Create Date: 2023-06-16 10:15:44.640317

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '39aea01afdd5'
down_revision = '3b1445711430'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contender_email', table_name='contender')
    op.drop_table('contender')
    op.drop_table('employer')
    op.add_column('hr_search', sa.Column('email', sa.String(), nullable=False))
    op.create_index(op.f('ix_hr_search_email'), 'hr_search', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hr_search_email'), table_name='hr_search')
    op.drop_column('hr_search', 'email')
    op.create_table('employer',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hunter_site_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hr_search_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['hr_search_id'], ['hr_search.id'], name='employer_hr_search_id_fkey'),
    sa.ForeignKeyConstraint(['hunter_site_id'], ['hunter_site.id'], name='employer_hunter_site_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='employer_pkey')
    )
    op.create_table('contender',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hunter_site_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('birthday', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('code_style', postgresql.ENUM('python', 'java', 'js', 'ruby', 'go', 'c', 'rust', name='codestyle'), autoincrement=False, nullable=False),
    sa.Column('reg_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('about_me', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('experience', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('owned_tech', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('selery', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['hunter_site_id'], ['hunter_site.id'], name='contender_hunter_site_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='contender_pkey')
    )
    op.create_index('ix_contender_email', 'contender', ['email'], unique=False)
    # ### end Alembic commands ###
