"""DB create

Revision ID: 3b1445711430
Revises: 
Create Date: 2023-06-15 11:55:06.679674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b1445711430'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hunter_site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contender',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hunter_site_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('code_style', sa.Enum('python', 'java', 'js', 'ruby', 'go', 'c', 'rust', name='codestyle'), nullable=False),
    sa.Column('reg_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('about_me', sa.String(), nullable=False),
    sa.Column('experience', sa.Float(), nullable=False),
    sa.Column('owned_tech', sa.String(), nullable=False),
    sa.Column('selery', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['hunter_site_id'], ['hunter_site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contender_email'), 'contender', ['email'], unique=True)
    op.create_table('hr_search',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hunter_site_id', sa.Integer(), nullable=True),
    sa.Column('experience', sa.Float(), nullable=False),
    sa.Column('owned_tech', sa.String(), nullable=False),
    sa.Column('selery', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['hunter_site_id'], ['hunter_site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hunter_site_id', sa.Integer(), nullable=True),
    sa.Column('hr_search_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hr_search_id'], ['hr_search.id'], ),
    sa.ForeignKeyConstraint(['hunter_site_id'], ['hunter_site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employer')
    op.drop_table('hr_search')
    op.drop_index(op.f('ix_contender_email'), table_name='contender')
    op.drop_table('contender')
    op.drop_table('hunter_site')
    # ### end Alembic commands ###
